/**
 * Valid filter properties available for historical trend queries.
 */
export type TrendsFilter =
  | 'all'
  | 'asn'
  | 'city'
  | 'country'
  | 'cpe'
  | 'has_ipv6'
  | 'has_screenshot'
  | 'has_ssl'
  | 'has_vuln'
  | 'hash'
  | 'hostname'
  | 'http.component'
  | 'http.component_category'
  | 'http.favicon.hash'
  | 'http.html_hash'
  | 'http.robots_hash'
  | 'http.securitytxt'
  | 'http.status'
  | 'http.title'
  | 'http.waf'
  | 'ip'
  | 'isp'
  | 'net'
  | 'org'
  | 'os'
  | 'port'
  | 'product'
  | 'region'
  | 'screenshot.label'
  | 'ssh.fingerprint'
  | 'ssl'
  | 'ssl.alpn'
  | 'ssl.cert.fingerprint'
  | 'ssl.cert.issuer.cn'
  | 'ssl.cert.serial'
  | 'ssl.cert.subject.cn'
  | 'ssl.ja3s'
  | 'ssl.jarm'
  | 'ssl.version'
  | 'state'
  | 'tag'
  | 'title'
  | 'version'
  | 'vuln'
  | (string & {});

/**
 * Represents a historical trend filter, optionally including a specific search value.
 */
export type TrendsFilterValue = TrendsFilter | `${TrendsFilter}:${string}` | (string & {});

/**
 * Valid filter properties available for standard search queries.
 */
export type SearchFilter =
  | 'all'
  | 'asn'
  | 'asset'
  | 'bitcoin.ip'
  | 'bitcoin.ip_count'
  | 'bitcoin.port'
  | 'bitcoin.version'
  | 'city'
  | 'cloud.provider'
  | 'cloud.region'
  | 'cloud.service'
  | 'country'
  | 'cpe'
  | 'device'
  | 'domain'
  | 'geo'
  | 'google_ads'
  | 'google_analytics'
  | 'google_tag_manager'
  | 'has_ipv6'
  | 'has_screenshot'
  | 'has_ssl'
  | 'has_vuln'
  | 'hash'
  | 'hostname'
  | 'http.component'
  | 'http.component_category'
  | 'http.dom_hash'
  | 'http.favicon.hash'
  | 'http.headers_hash'
  | 'http.html'
  | 'http.html_hash'
  | 'http.robots_hash'
  | 'http.securitytxt'
  | 'http.server_hash'
  | 'http.status'
  | 'http.title'
  | 'http.title_hash'
  | 'http.waf'
  | 'ip'
  | 'isp'
  | 'link'
  | 'meta_pixel'
  | 'net'
  | 'ntp.ip'
  | 'ntp.ip_count'
  | 'ntp.more'
  | 'ntp.port'
  | 'open_dir.extension'
  | 'open_dir.hash'
  | 'org'
  | 'os'
  | 'port'
  | 'postal'
  | 'product'
  | 'region'
  | 'scan'
  | 'screenshot.hash'
  | 'screenshot.label'
  | 'shodan.module'
  | 'snmp.contact'
  | 'snmp.location'
  | 'snmp.name'
  | 'ssh.hassh'
  | 'ssh.type'
  | 'ssl'
  | 'ssl.alpn'
  | 'ssl.cert.alg'
  | 'ssl.cert.expired'
  | 'ssl.cert.extension'
  | 'ssl.cert.fingerprint'
  | 'ssl.cert.issuer.cn'
  | 'ssl.cert.pubkey.bits'
  | 'ssl.cert.pubkey.type'
  | 'ssl.cert.serial'
  | 'ssl.cert.subject.cn'
  | 'ssl.chain_count'
  | 'ssl.cipher.bits'
  | 'ssl.cipher.name'
  | 'ssl.cipher.version'
  | 'ssl.ja3s'
  | 'ssl.jarm'
  | 'ssl.version'
  | 'state'
  | 'tag'
  | 'telnet.do'
  | 'telnet.dont'
  | 'telnet.option'
  | 'telnet.will'
  | 'telnet.wont'
  | 'tiktok_pixel'
  | 'version'
  | 'vuln'
  | 'x_pixel'
  | (string & {});
